### ISSUE TITLE
Assertion failure on inline code within quote

### ISSUE THREAD

**Issue by 197g** [oberien/pundoc#108]
Reproduction:

```
> Apparently, `1 +
> 1` equals crash.
```

> thread 'main' panicked at 'assertion failed: range.end == r.start || range.end + 1 == r.start', src/frontend/concat.rs:29:13

**Comment by oberien** [comment]
Yeah, just completely comment out that assertion, it's wrong in every aspect. It also has problems with indented code blocks. I should remove it and add a comment.
