### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by oberien** [oberien/pundoc#11]
**Decision: heradoc**

TODO:

- [ ] `s/pundoc/heradoc/g` ∀ files
- [ ] rename github repository
- [x] update github description (if needed)
- [ ] update repository urls in local git copies

This project has reached a state where we need to think about a possibly different name. If we ever want this tool to be used by more than 2 people, the ambiguity between `pundoc` and `pandoc` is too high. Here are some suggestions with their explanations:

1. `pundoc`: "pun" wrt. "pandoc" is pretty obvious. Unfortunately, they are very ambiguous, which is why we should look for something different.
2. `omnidoc`: "pan-" is a combining form for "all-", taken from the Greek. "omni-" is also a combining form with the same meaning, but it stems from Latin.
There is already a product called `omnidoc`, which is some medical device for documentation of gel. "OMNIDOC" and "OmniDoc" are registered trademarks in the US and KR respectively. "omnidoc" thus shouldn't be a problem, albeit maybe harder to search for.
3. `heradoc`: Pan is the Greek god of shepherds. Hera is a Greek goddess, the queen of gods. Hera > Pan, which means heradoc > pandoc ;) Furthermore, heradoc sounds a little like heretic, which would fit with the general view of the rust community regarding RIIR, which is exactly what we're doing here.
Heradoc is not a registered trademark, the closest to it would be THERADOC, so we're fine on that front. Heradoc *is* a German app for agriculture documentation though. However, I don't think that'll pose too much of an issue.
4. `maydoc`: "PAN-PAN is the international standard urgency signal that someone […] uses to declare that they have a situation that is urgent but, for the time being at least, does not pose an immediate danger to anyone's life or to the vessel itself." (thanks wikipedia) Similar is the word "Mayday", which is a stronger urgency signal requesting immediate highest priority. Thus `PANdoc` vs `MAYdoc`. Advantages are internationally equal pronunciation, two syllables (compared to 2 and 3 having three) and it's a soft word that's easier to say.
Maydoc is not trademarked in any way, there isn't even a similar existing trademark. On Google the first hit is a youtube channel with 0 subscribers, so the word is completely free for our use.

Here is a table, collecting all votes so far.

omnidoc | heradoc | maydoc
--- | --- | ---
3 | 2 | 3

**Comment by 197g** [comment]
Omnidoc is also registered for device class `Computer application software`. See [85893594](https://tsdr.uspto.gov/#caseNumber=85893594&caseSearchType=US_APPLICATION&caseType=DEFAULT&searchType=statusSearch)

**Comment by oberien** [comment]
85893594 is one of the TMs I was referring to as "OMNIDOC" being trademarked by the US. Only the capital form seems to be protected, not the lowercase form I suggested.

**Comment by 197g** [comment]
I would suppose that the difference between capital and non-capital form is generally considered small enough to be considered 'confusing similarity'. (Even when disregarding that the mark is registered as a word mark, without any regards to `font, size, or color` and while no expert on US trademark law, that should also include capitalization).

**Comment by oberien** [comment]
That means that omnidoc wouldn't be a wise choice. This leaves us with `heradoc` and `maydoc`. Which one do you prefer?

**Comment by 197g** [comment]
`heradoc`, it also spares us potential jokes of `maynotdoc` if it isn't working ^^

**Comment by oberien** [comment]
I already registered the domain `pundoc.de` some time ago, which isn't a big deal if we're going to switch the name. The problem is that both `heradoc.de` and `maydoc.de` are already taken. Thus I'm not sure if we should choose one of those or if we should switch in the first place.

**Comment by 197g** [comment]
`heradoc.org` seems free ( and `heradoc.io`, `heradoc.rs` )
