### ISSUE TITLE
Can't install without using `--locked`

### ISSUE THREAD

**Issue by WorldSEnder** [oberien/pundoc#133]
Expected behavior: `cargo install --path .` works after cloning the library

Actual behavior: The dependency on `str-concat = "0.1.4"` refers to a yanked version of `str-concat` and should probably be updated to `str-concat = "0.2.0"`. `cargo install` complains, unless given the `--locked` flag.

**Comment by oberien** [comment]
Thank you for the report, it should be fixed on the latest master.
