### ISSUE TITLE
Cargo.toml refers to non-existent revision of pulldown-cmark

### ISSUE THREAD

**Issue by 197g** [oberien/pundoc#14]
Revision `a64f578e71a860503a9ffb62efcead12fdb5868c` does not exist in github.com/oberien/pulldown-cmark

Possibly just a forgotten push.

**Comment by oberien** [comment]
Actually a deleted branch because raphlinus/pulldown-cmark#147 was merged :) We can probably just depend on raphlinus/pulldown-cmark commit 07863e9e54cfcb108693ca1ab64967b5ad7bd952 .

**Comment by 197g** [comment]
That version of pulldown-cmark requires another small adjustment. Options are not exposed as constants in the crate level but as constants in an `Options` struct instead. Should I just fix it directly on master or pull request?

**Comment by oberien** [comment]
Just fix it directly on master, this shouldn't need to go through a PR.

**Comment by 197g** [comment]
Fixed in b3ebff6aa89523c8e9126a15a39614132995d6c4
