### ISSUE TITLE
Labels, References, Element-Config and Figures

### ISSUE THREAD

**Issue by oberien** [oberien/pundoc#16]
* currently label and reference systems are inconsistent with each other
* somewhat enforced label prefix
    * actually not really
    * complicates system unnecessarily
* labels are generated in backend
    * no syntax enforced
    * could result in different label syntax in different backends

TODOs:

- [x] References rework (frontend)
- [x] cskvp parsing (single values and key=value pairs)
- [x] Refactor backend to destructure its argument instead of accessing all of its values.
  This makes adding new members to a struct result in an error everywhere, which requires us integrating it everywhere.
- [x] Labels in all elements (frontend)
    - [x] Label parsing
    - [x] Remove label parsing from backend
- [x] Figures
    - [x] `figures` config option
- [x] Element-Config in all elements

## New system suggestion:

Label: Definition of label
Reference: Reference to a label

References:

* 2 Namespaces:
    * Biber (starts with `@`)
        * biber single: `[@foo]`, `[@foo 42-69, 322]`, `[@foo Chapter 13]`
            * `BiberSingle(Cow, Option<Cow>)`
        * biber multiple: `[@foo 21-23,25, @bar Chapters 10-15]`
            * `BiberMultiple(Vec<(reference, Option<attributes>)>)`
    * Links (starts with `#` or `^`)
        * all links are equal
        * Footnotes: `[^foo]`
            * part of Links with prefix `fnote:`
            * `^foo` is translated to `fnote:foo`
            * should still be referenced as `[^foo]`, otherwise it's a cref instead of a footnotemark
        * cref: `[#foo]`
            * `#foo` is just `#foo`
            * `InterLink(LabelReference)` (uppercase=false)
        * Cref: `[#Foo]`
            * `InterLink(LabelReference)` (uppercase=true)
        * cref / Cref with content: `[text][#foo]`, `[text](#foo)`
            * `InterLinkWithContent(LabelReference)`
        * Text: `[text][doesn't start with # or ^]`
            * output as plain text
            * issue warning (blocked on #12)
        * anything else: `[foo.md]`, `[anything not captured]`
            * `Url`
        * anything else with content: `[text](file.md)`, `[text](anything not captured)`
            * `UrlWithContent`

Labels:

* generated and added to elements in frontend
    * common label syntax
* Fotnotes: `[^foo]: Text for footnote`
    * translated to `fnote:foo`
* Automatic labels for each section:
    * `# Heading Foo$() Bar` translated to `heading-foo-bar`
    * all chars converted to lowercase
    * `" "` converted to `"-"`
    * `[^a-zA-Z0-9-_ ]` converted to `""`
* Inline labels: `{#foo}`
    * translated to label `foo`
* Labels after section: `# Heading {#label-for-heading}`
    * translated to `label-for-heading`
* Prefix-style label must be at the beginning of a paragraph (empty line before) and either end the paragraph (empty line after) or be followed by a SoftBreak (line break)
* Labels before Image / Table / Code / Graphviz (empty line required before table):
  ```md
  {#label,config...}

  Heading A | Heading B
  --- | :-:
  Cell 1 | Cell 2
  ```
* Labels for Code / Graphviz, different way (for easier compatibility with other MD parsers):
  ````md
  ```language,#foo,config...
  fn main() {}
  ```
  ````
* Labels before Image (can't be on its own paragraph, so must be followed by linebreak followed directly by image):
  ```md
  {#fancy-image}
  ![alt-text](link "title")
  ```

Element-Config:

* Config: cskvp (comma-seperated key-value pairs)
    * all: 
        * label: `#foo`
        * `figure=true` / `figure=false`
            * Figure Caption: `caption=`
    * Image / Graphviz: `scale=`, `width=`, `height=`
    * Code
    * Table

Figure handling:

* Add new config option `figures=`
    * `true`: images / graphviz / code / tables default to being wrapped in figures
    * `false`: images / graphviz / code / tables default to being inline
* if `figure=true` is specified (or `figure=false` is not specified but `figures=true` configured in the config):
    * put label within figure (instead of within element)
    * wrap element in Figure Tag
    ```rust
    Event::Start(Tag::Figure(label=…, …))
    // item
    Event::End(Tag::Figure(…))
    ```

Elements with Config:

* Have different possible config within each struct

```rust
struct Image {
    …,
    label = Cow,
    scale = …,
    width = …,
    height = …,
}
```

**Comment by 197g** [comment]
One shortcoming that should definitely be fixed as well: Labels should be able to contain literal commata `,`. These are currently always semantic context for the attribute parser and unusable.

**Comment by oberien** [comment]
This will be added later on when `cskvp.rs` adds support for double-quoted keys and values. (#19)

Edit: While that makes sense for config options, why should labels contain commas or spaces or similar?

**Comment by 197g** [comment]
For example when a caption wants to `\cite{}` more than one source, or with a page number. Or when the caption contains math etc.

**Comment by 197g** [comment]
Edit: I think I've not been precise. It's about attributes in general, not labels specifically. Some contexts could want to set titles with an attribute (i.e. latex amsthm).
