### ISSUE TITLE
What to do with Link / Image Title and Alt-Text?

### ISSUE THREAD

**Issue by oberien** [oberien/pundoc#18]
With #16 there is a common and defined way for all elements to have config, including a label, and captions for figures. The old idea of an image's title was to be used as label and its alt-text as config. This may now be obsolete, especially because the config can contain a label.

So what shall we do with the title of links and images, and the alt-text of images?

**Comment by moritzuehling** [comment]
My personal recommendation would be to actually use those features in the way they are intended:

- Use the alt text as an accessibility feature (for example, as documented [in this SO answer](https://tex.stackexchange.com/questions/75102/need-alt-text-for-images-in-pdf-for-screen-readers/75104#75104).
- Use the title as a tooltip using [pdftooltip](https://tex.stackexchange.com/a/75151)

This way the features are very compatible with normal markdown, and you give people a way to be nice.
