### ISSUE TITLE
Fancy error messages

### ISSUE THREAD

**Issue by oberien** [oberien/pundoc#21]
Related to #13 we should have some sort of `Context` object, which contains the bounds of the element that pulldown-cmark is currently parsing such that we can display fancy error messages.

**Comment by 197g** [comment]
See https://github.com/oberien/pundoc/tree/error_origin although that currently fails for links etc, where the interesting part is inside the start and end tag, not between them.

**Comment by oberien** [comment]
For diagnostics we should probably use the `codespan` and `codespan-reporting` crates. My current idea is to first fix #64, which will make this somewhat easier to reason about.

1. First, we need to use the `OffsetIter` of pulldown-cmark and make all iterator wrappers return `Item = (Event, Range<usize>)` instead of just `Item = Event`.
2. All CodeGenUnits should return a `Result` with a custom `Error` type.
3. In the generator, if any CodeGenUnit returned an `Error` from any function, that error is converted to a diagnostic and emitted.
4. The generator will try to skip over that event, or over the whole block if a `Start`-event errors.

Unresolved Question:

* How to emit errors in the frontend / generator / non-CodeGenUnits?

**Comment by oberien** [comment]
Just a short preliminary result. I guess that looks good enough :)
![screenshot20190328175635](https://user-images.githubusercontent.com/4820508/55177354-53ccb100-5183-11e9-8aad-dd949adcd089.png)
