### ISSUE TITLE
Include resolution should not consider missing file a bug

### ISSUE THREAD

**Issue by 197g** [oberien/pundoc#75]
The resolution of the include path from some markdown should not yet require such file to be present. Unfortunately, it does as `Path::canonicalize` requires it to resolve links and more. Instead of relying on path resolution relative to an ad-hoc set working directory, the path components should be iterated and pushed to the custom working directory, also eliminating the temporary adjustment to global state.

Besides, the `path` component of an Url should already be normalized from any `..` components and current resolution works on `Unix` style paths but has it been tested on Windows? Might be confusing, since the url of course contains `/` separator but the correct separator is `\`.

https://github.com/oberien/heradoc/blob/e829fefd112608e6f87f104691ea3db18d12423a/src/resolve/source.rs#L205

Diagnostics also consider a missing file (in #69 anyways) but that can not be tested due to this.

**Comment by 197g** [comment]
Canonicalization is potentially important to determine access rights, so it's better to keep it in. But a failure in the resolution should not be considered an implementation bug and rather needs a more diverse error type. See #77

**Comment by oberien** [comment]
Fixed in #77
