### ISSUE TITLE
Resolve local links in file's workdir but also from project root

### ISSUE THREAD

**Issue by oberien** [oberien/pundoc#89]
Currently if I have an image in `images/image.png` and want to include it in `chapters/chapter.md` as `[include images/image.png]`, it isn't resolved correctly, because the resolver currently only resolves in the context of the file, which in this case is starting from the directory `chapters/`. Our `to_path` implementation ignores any backreferences, so `../images/image.png` also can't be used.

We should resolve local includes first from the current context's path, and then, if it wasn't found, from the project's working directory.

**Comment by 197g** [comment]
This is a bug here:

https://github.com/oberien/heradoc/blob/0da47c6031e652e114592b86315f50498de34f50/src/resolve/source.rs#L110-L111

The `Source` expects to get the working directory but instead retrieves the path of the exact resource that requested the resolution. The original resolution works as expect, i.e. https://github.com/oberien/heradoc/blob/0da47c6031e652e114592b86315f50498de34f50/src/resolve/mod.rs#L50 appends correctly to form `heradoc://document/images/image.png`.

Going to self-assign and fix this, it seems like it could affect working in subdirectories beyond the scope  that the issue description implies. The resolver is going to get a better test suite as well.

**Comment by 197g** [comment]
I think the `LocalRelative`-variant of `Context` should contain two member: A working directory as a base path and a relative member of it. Utility constructor for this would also fix the perceived weirdness of all current test cases where their context is constructed by manually appending filepaths to the chosen working directory.

Incidentally, it also improves the detection of local absolute paths that can be made relative by allowing use of `Path::strip_prefix` with the working dir!

**Comment by 197g** [comment]
There is a fair amount of confusion around `Context` and `SourceGroup`. Some parts of the code treat the path within `Context::LocalAbsolute` as also containing the parent directory of the local file but to my understanding I had assumed it to work like a `file:///` and thus be pretty much identical to the `SourceGroup` version (modulo some path canonicalization).

It seems that the only code currently inspecting the field is `Source::new` when the url points to a document. But then the result will always be `LocalRelative` and get denied as a permission violation. That seems weird?

I'll change it and see if that breaks anything.

**Comment by oberien** [comment]
At this point I think the whole resolver needs another big refactor, to get rid of the arbitrary distinction between Source, SourceGroup, Context and co. It doesn't need to abstract over everything, as we don't need it to be as modular as first intended.
