### ISSUE TITLE
Keep temp_dir on error / panic

### ISSUE THREAD

**Issue by oberien** [oberien/pundoc#96]
If an error / panic results in no output file, we should keep the temp_dir instead of deleting it. This could be done either by wrapping it in `ManuallyDrop` and dropping it on success, or with `mem::forget` in case of a problem.

**Comment by 197g** [comment]
Duplicate of #5 :smiley:

**Comment by oberien** [comment]
Oh, we have enough issues for multiple pages. That's why Ctrl+F didn't turn up anything…
